### PR TITLE
LPS-123413 NullPointerException is thrown when deleting user

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-123413](https://issues.liferay.com/browse/LPS-123413).<br/><br/>Hi @istvansajtos, will you please look over my solution and double-check that it fixes the issue as you understand it\? We have run into this issue in a number of other places and have solved it in the same way. Please let me know if you have any questions. Thank you!<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by istvansajtos** [comment]
Thank @drewbrokke , I am checking it!

**Comment by istvansajtos** [comment]
Hey @drewbrokke ,

Your solution looks exactly what I need. :)

Could you please forward it to Brian as you would normally do?

Thank you!

**Comment by drewbrokke** [comment]
@istvansajtos glad it works! If it works for you, we can just forward this pull.

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
