### PR TITLE
LPS-69935 with test

### PR DESCRIPTION
**Pull request by lipusz**
Hi Pisti,

I added a test to UserFinderTest based on SocialRelationLocalServiceTest, but for some reason, it returns 0 when it should return 1 in testFindBySocialUsers.

Can you please look into this? We should have a test for the issue.

Thanks!
Tibi

This is what I'm using to run the tests on PostgreSQL locally:
**portal-test-ext.properties**
```properties
jdbc.default.driverClassName=org.postgresql.Driver
jdbc.default.url=jdbc:postgresql://localhost:5432/lportal-master
jdbc.default.username=postgres
jdbc.default.password=postgres
liferay.home=/home/tibusz/liferay/bundles/master
module.framework.base.dir=/home/tibusz/liferay/bundles/master/osgi
```

FYI: CI runs the tests on all DBs for each pull.

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by istvansajtos** [comment]
Hi Tibi,

I had some difficulties running the tests. Hopefully I can finish this tomorrow.

Sorry for the delay.

**Comment by istvansajtos** [comment]
Hi Tibi,

The problem was simply the use of WorkflowConstants.STATUS_ANY, which has the associalted value '-1'. For the approved status we need to use WorkflowConstants.STATUS_APPROVED with its associated value '0'.

BTW, didn't you want to pass a comparator object to the findBySocialUsers() method? Otherwise the fixed code section won't be executed.

Thanks!

**Comment by istvansajtos** [comment]
[lipusz#165](https://github.com/lipusz/liferay-portal/pull/165)

**Pull request closed without merging**
