### PR TITLE
LPS-92932 Indirect permission checks in *LocalServiceImpl classes

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-92932](https://issues.liferay.com/browse/LPS-92932).<br><br>Hey @istvansajtos, can you please double-check my changes to the test cases? If they look good to you, go ahead and forward to Brian.<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
Just started reviewing. :)

**Comment by istvansajtos** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/79497

Thank you!

**Pull request closed without merging**
