### PR TITLE
LPS-95644 Separate articles per company to ensure that any article in the interval is indexed with the same company

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
Just started reviewing. :)

**Comment by istvansajtos** [comment]
Hi @dacousalr ,

Thanks for spotting the bug. Your changes look completely fine to me.

Could you please forward it to Brian?

Thank you.

**Comment by dacousalr** [comment]
Thank you so much, @istvansajtos 

Kudos to @jorgediaz-lr

**Pull request closed without merging**
