### PR TITLE
[TECHNICAL SUPPORT] LPS-70181

### PR DESCRIPTION
**Pull request by amadeafejes**
https://issues.liferay.com/browse/LPS-70181

### CODE REVIEW

**Comment by amadeafejes** [comment]
ci:retest

**Comment by amadeafejes** [comment]
ci:retest

**Comment by amadeafejes** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Ami,

Please, rebase your branch to latest HEAD and update in your origin with ```--force``` option.

**Comment by lipusz** [comment]
Ignore my comment, I didn't realized that you had already sent another pull. But that one may also require a rebase. ;-)

**Comment by lipusz** [comment]
#16

**Pull request closed without merging**
