### PR TITLE
LPS-92932 Indirect permission checks in *LocalServiceImpl classes

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-92932](https://issues.liferay.com/browse/LPS-92932).<br><br>Hey @istvansajtos, this looks good. Can you please add a regression test case on top of this branch? Once you do we shouuld be good to go on this.<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
Hi @drewbrokke, 

Sure. I will return to this soon to add some tests.

**Comment by drewbrokke** [comment]
Hey @istvansajtos, is there any update on the tests for this issue?  Thanks!

**Comment by istvansajtos** [comment]
Hi @drewbrokke, I was busy with some urgent tasks recently, sorry for the lack of updates. Now I will be on PTO until next Monday. I will return to this afterwards.

Thanks for your patience.

**Comment by drewbrokke** [comment]
Hey @istvansajtos, any update on the tests for this issue?

**Comment by istvansajtos** [comment]
Hi Drew,

Sorry for postponing this so long. This week I can dedicate some time to complete this with tests.

**Comment by drewbrokke** [comment]
Thanks @istvansajtos!

**Comment by istvansajtos** [comment]
Updated and resent as https://github.com/liferay/liferay-portal/pull/3580

**Pull request closed without merging**
