### PR TITLE
[TECHNICAL SUPPORT] LPS-70181

### PR DESCRIPTION
**Pull request by amadeafejes**
https://issues.liferay.com/browse/LPS-70181

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Pisti,

Please, proceed with this pull today. Thanks!

**Comment by istvansajtos** [comment]
Sorry for the delay!

Just started reviewing. :)

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
ci:reopen

**Comment by istvansajtos** [comment]
[#17](https://github.com/istvansajtos/liferay-portal/pull/17)

**Pull request closed without merging**
